export const APP_LOAD = 'APP_LOAD';
export const ASYNC_END = 'ASYNC_END';
export const ASYNC_START = 'ASYNC_START';
export const GET_DATA = 'GET_DATA';
export const CHARACTERS_PAGE_LOADED = 'CHARACTERS_PAGE_LOADED';
export const CHARACTERS_PAGE_UNLOADED = 'CHARACTERS_PAGE_UNLOADED';
export const CHARACTERS_EPISODE_LOADED = 'CHARACTERS_EPISODE_LOADED';
export const CHARACTERS_EPISODE_UNLOADED = 'CHARACTERS_EPISODE_UNLOADED';